# Generated by Django 5.2.4 on 2025-07-31 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_school_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_n0',
            new_name='roll_no',
        ),
    ]
